/**:
  ros__parameters:
    # Spot Login Information
    username: "user"
    password: "your_spot_password"
    hostname: "192.168.1.100"  # Replace with your Spot's IP

    # Status Updates from Spot
    metrics_rate: 0.04
    lease_rate: 1.0
    async_tasks_rate: 10.0
    robot_state_rate: 50.0
    image_rate: 10.0

    # Boolean parameters
    auto_claim: True
    auto_power_on: False
    auto_stand: False

    # Estop Parameters
    estop_timeout: 9.0
    start_estop: False

    preferred_odom_frame: "vision"
    tf_root: "body"

    # Robot identification
    spot_name: "gouger"

    cmd_duration: 0.25
    arm_cmd_duration: 1.0
    rgb_cameras: True
    initialize_spot_cam: False

    use_velodyne: True
    velodyne_rate: 10.0

    # Virtual camera parameters for image stitching
    virtual_camera_intrinsics: [385.0, 0.0, 315.0, 0.0, 385.0, 844.0, 0.0, 0.0, 1.0]
    virtual_camera_projection_plane: [-0.15916, 0.0, 0.987253]
    virtual_camera_plane_distance: 0.5
    stitched_image_row_padding: 1182

    gripperless: False
    publish_graph_nav_pose: True